/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;

/**
 *
 * @author lanz1
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    
    Color defaultColor, clickedColor;
    
    public dashboard() {
        initComponents();
        
        defaultColor = new Color(13, 36, 51);
        clickedColor = new Color(240, 151, 57);
        
        menuTransaksi.setBackground(defaultColor);
        //detailMenu.setText("Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuTransaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuStok = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuBarang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuSatuan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuPengguna = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menuLaporan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        detailMenu = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(13, 36, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 250, -1));

        menuTransaksi.setBackground(new java.awt.Color(13, 36, 51));
        menuTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTransaksiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuTransaksiMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(13, 36, 51));
        jLabel4.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-accounting_1.png"))); // NOI18N
        jLabel4.setText("Transaksi Penjualan");

        javax.swing.GroupLayout menuTransaksiLayout = new javax.swing.GroupLayout(menuTransaksi);
        menuTransaksi.setLayout(menuTransaksiLayout);
        menuTransaksiLayout.setHorizontalGroup(
            menuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuTransaksiLayout.setVerticalGroup(
            menuTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        menuStok.setBackground(new java.awt.Color(13, 36, 51));
        menuStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuStokMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(13, 36, 51));
        jLabel5.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-commodity.png"))); // NOI18N
        jLabel5.setText("Stok");

        javax.swing.GroupLayout menuStokLayout = new javax.swing.GroupLayout(menuStok);
        menuStok.setLayout(menuStokLayout);
        menuStokLayout.setHorizontalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        menuStokLayout.setVerticalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 40));

        menuBarang.setBackground(new java.awt.Color(13, 36, 51));
        menuBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBarangMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(13, 36, 51));
        jLabel6.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add_subnode.png"))); // NOI18N
        jLabel6.setText("Master Barang");

        javax.swing.GroupLayout menuBarangLayout = new javax.swing.GroupLayout(menuBarang);
        menuBarang.setLayout(menuBarangLayout);
        menuBarangLayout.setHorizontalGroup(
            menuBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        menuBarangLayout.setVerticalGroup(
            menuBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 40));

        menuSatuan.setBackground(new java.awt.Color(13, 36, 51));
        menuSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSatuanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSatuanMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(13, 36, 51));
        jLabel7.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add_subnode.png"))); // NOI18N
        jLabel7.setText("Master Satuan");

        javax.swing.GroupLayout menuSatuanLayout = new javax.swing.GroupLayout(menuSatuan);
        menuSatuan.setLayout(menuSatuanLayout);
        menuSatuanLayout.setHorizontalGroup(
            menuSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSatuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        menuSatuanLayout.setVerticalGroup(
            menuSatuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSatuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        menuPengguna.setBackground(new java.awt.Color(13, 36, 51));
        menuPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPenggunaMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(13, 36, 51));
        jLabel8.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add_subnode.png"))); // NOI18N
        jLabel8.setText("Master Pengguna");

        javax.swing.GroupLayout menuPenggunaLayout = new javax.swing.GroupLayout(menuPengguna);
        menuPengguna.setLayout(menuPenggunaLayout);
        menuPenggunaLayout.setHorizontalGroup(
            menuPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        menuPenggunaLayout.setVerticalGroup(
            menuPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 250, 40));

        menuLaporan.setBackground(new java.awt.Color(13, 36, 51));
        menuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuLaporanMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(13, 36, 51));
        jLabel9.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-business_report.png"))); // NOI18N
        jLabel9.setText("Laporan Penjualan");

        javax.swing.GroupLayout menuLaporanLayout = new javax.swing.GroupLayout(menuLaporan);
        menuLaporan.setLayout(menuLaporanLayout);
        menuLaporanLayout.setHorizontalGroup(
            menuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLaporanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        menuLaporanLayout.setVerticalGroup(
            menuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(menuLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 480));

        jPanel3.setBackground(new java.awt.Color(240, 151, 57));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close_window.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Point Of Sales");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        detailMenu.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        detailMenu.setForeground(new java.awt.Color(255, 255, 255));
        detailMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-shop.png"))); // NOI18N
        detailMenu.setText("Dashboard");
        jPanel3.add(detailMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 90));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(733, 579));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 690, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(933, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void menuTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMousePressed
        // TODO add your handling code here:
        
        menuTransaksi.setBackground(clickedColor);
        menuStok.setBackground(defaultColor);
        menuBarang.setBackground(defaultColor);
        menuSatuan.setBackground(defaultColor);
        menuPengguna.setBackground(defaultColor);
        
        detailMenu.setText("Transaksi Penjualan");
                
    }//GEN-LAST:event_menuTransaksiMousePressed

    private void menuStokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStokMousePressed
        // TODO add your handling code here:
        menuTransaksi.setBackground(defaultColor);
        menuStok.setBackground(clickedColor);
        menuBarang.setBackground(defaultColor);
        menuSatuan.setBackground(defaultColor);
        menuPengguna.setBackground(defaultColor);
      
        detailMenu.setText("Stok Masuk Barang");
    }//GEN-LAST:event_menuStokMousePressed

    private void menuBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarangMousePressed
        // TODO add your handling code here:
        menuTransaksi.setBackground(defaultColor);
        menuStok.setBackground(defaultColor);
        menuBarang.setBackground(clickedColor);
        menuSatuan.setBackground(defaultColor);
        menuPengguna.setBackground(defaultColor);

        detailMenu.setText("Kelola Data Barang");
              
    }//GEN-LAST:event_menuBarangMousePressed

    private void menuSatuanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSatuanMousePressed
        // TODO add your handling code here:
        menuTransaksi.setBackground(defaultColor);
        menuStok.setBackground(defaultColor);
        menuBarang.setBackground(defaultColor);
        menuSatuan.setBackground(clickedColor);
        menuPengguna.setBackground(defaultColor);
        
        detailMenu.setText("Kelola Satuan Barang");
                    
    }//GEN-LAST:event_menuSatuanMousePressed

    private void menuPenggunaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPenggunaMousePressed
        // TODO add your handling code here:
        menuTransaksi.setBackground(defaultColor);
        menuStok.setBackground(defaultColor);
        menuBarang.setBackground(defaultColor);
        menuSatuan.setBackground(defaultColor);
        menuPengguna.setBackground(clickedColor);
        
        detailMenu.setText("Kelola Pengguna");        
    }//GEN-LAST:event_menuPenggunaMousePressed

    private void menuBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarangMouseClicked
        // TODO add your handling code here:
        MasterBarang frmMasterBarang = new MasterBarang();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterBarang).setVisible(true);        
    }//GEN-LAST:event_menuBarangMouseClicked

    private void menuSatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSatuanMouseClicked
        // TODO add your handling code here:
         MasterJenis frmMasterSatuan = new MasterJenis();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterSatuan).setVisible(true);  
    }//GEN-LAST:event_menuSatuanMouseClicked

    private void menuTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTransaksiMouseClicked
        // TODO add your handling code here:
  // TODO add your handling code here:
//        TransaksiPenjualan frmTransaksi = new TransaksiPenjualan();
//        jDesktopPane1.removeAll();
//        jDesktopPane1.add(frmTransaksi).setVisible(true);                
    }//GEN-LAST:event_menuTransaksiMouseClicked

    private void menuLaporanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLaporanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLaporanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menuBarang;
    private javax.swing.JPanel menuLaporan;
    private javax.swing.JPanel menuPengguna;
    private javax.swing.JPanel menuSatuan;
    private javax.swing.JPanel menuStok;
    private javax.swing.JPanel menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
