/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import login.loginForm;

/**
 *
 * @author lanz1
 */
public class DashboardGudang extends javax.swing.JFrame {

    
    Color defaultColor, clickedColor;
     Color penDefault, penEnter, penClick, fontColorClicked,fontColorDefault;
    
    public DashboardGudang() {
        initComponents();
       defaultColor = new Color(19,47,37);
        clickedColor = new Color(52,132,103);
      
        penDefault = new Color(255,255,255);
        fontColorDefault = new Color(52,132,103);
        penEnter = new Color(52,132,103);
        fontColorClicked = new Color(255,255,255);
        penClick = new Color(52, 132, 103);
        
        jPanelLogout.setBackground(penDefault);
        
        //menuTransaksi.setBackground(defaultColor);
        //detailMenu.setText("Dashboard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        menuStok = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        kelolaJenis = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        textLogout = new javax.swing.JLabel();
        menuDashboard = new javax.swing.JPanel();
        label_2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_3 = new javax.swing.JLabel();
        kelolaBarang = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        detailMenu = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(19, 47, 37));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuStok.setBackground(new java.awt.Color(19, 47, 37));
        menuStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStokMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuStokMousePressed(evt);
            }
        });

        label3.setBackground(new java.awt.Color(13, 36, 51));
        label3.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Stok.png"))); // NOI18N
        label3.setText("Stock Barang");

        javax.swing.GroupLayout menuStokLayout = new javax.swing.GroupLayout(menuStok);
        menuStok.setLayout(menuStokLayout);
        menuStokLayout.setHorizontalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        menuStokLayout.setVerticalGroup(
            menuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(menuStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 60));

        kelolaJenis.setBackground(new java.awt.Color(19, 47, 37));
        kelolaJenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaJenisMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kelolaJenisMousePressed(evt);
            }
        });

        label8.setBackground(new java.awt.Color(13, 36, 51));
        label8.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stockmanage.png"))); // NOI18N
        label8.setText("Kelola Jenis");

        javax.swing.GroupLayout kelolaJenisLayout = new javax.swing.GroupLayout(kelolaJenis);
        kelolaJenis.setLayout(kelolaJenisLayout);
        kelolaJenisLayout.setHorizontalGroup(
            kelolaJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaJenisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        kelolaJenisLayout.setVerticalGroup(
            kelolaJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(kelolaJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 250, 60));

        jPanelLogout.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseReleased(evt);
            }
        });

        textLogout.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        textLogout.setForeground(new java.awt.Color(52, 132, 103));
        textLogout.setText("Logout");

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(textLogout)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.add(jPanelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 230, -1));

        menuDashboard.setBackground(new java.awt.Color(19, 47, 37));
        menuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDashboardMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuDashboardMousePressed(evt);
            }
        });

        label_2.setBackground(new java.awt.Color(13, 36, 51));
        label_2.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label_2.setForeground(new java.awt.Color(255, 255, 255));
        label_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboardmenu.png"))); // NOI18N
        label_2.setText("Dashboard");

        javax.swing.GroupLayout menuDashboardLayout = new javax.swing.GroupLayout(menuDashboard);
        menuDashboard.setLayout(menuDashboardLayout);
        menuDashboardLayout.setHorizontalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        menuDashboardLayout.setVerticalGroup(
            menuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        label_3.setBackground(new java.awt.Color(13, 36, 51));
        label_3.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        label_3.setForeground(new java.awt.Color(255, 255, 255));
        label_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_3.setText("Alvio Irawan");
        jPanel13.add(label_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 90, 230, 30));

        kelolaBarang.setBackground(new java.awt.Color(19, 47, 37));
        kelolaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelolaBarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kelolaBarangMousePressed(evt);
            }
        });

        label4.setBackground(new java.awt.Color(13, 36, 51));
        label4.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warehouse.png"))); // NOI18N
        label4.setText("Kelola Barang");

        javax.swing.GroupLayout kelolaBarangLayout = new javax.swing.GroupLayout(kelolaBarang);
        kelolaBarang.setLayout(kelolaBarangLayout);
        kelolaBarangLayout.setHorizontalGroup(
            kelolaBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelolaBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        kelolaBarangLayout.setVerticalGroup(
            kelolaBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel13.add(kelolaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 60));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 560));

        jPanel3.setBackground(new java.awt.Color(52, 132, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close_window.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        detailMenu.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        detailMenu.setForeground(new java.awt.Color(255, 255, 255));
        detailMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        detailMenu.setText("Home");
        jPanel3.add(detailMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, -1));

        jPanel12.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 50));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(733, 579));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel12.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 690, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(940, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuStokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStokMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(clickedColor);
        kelolaBarang.setBackground(defaultColor);
        kelolaJenis.setBackground(defaultColor);
        menuDashboard.setBackground(defaultColor);

        detailMenu.setText("Stok Masuk Barang");
    }//GEN-LAST:event_menuStokMousePressed

    private void kelolaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaBarangMouseClicked
        // TODO add your handling code here:
        MasterBarang frmMasterBarang = new MasterBarang();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterBarang).setVisible(true);
    }//GEN-LAST:event_kelolaBarangMouseClicked

    private void kelolaBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaBarangMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(defaultColor);
        kelolaBarang.setBackground(clickedColor);
        kelolaJenis.setBackground(defaultColor);
        menuDashboard.setBackground(defaultColor);

        detailMenu.setText("Kelola Data Barang");

    }//GEN-LAST:event_kelolaBarangMousePressed

    private void kelolaJenisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaJenisMouseClicked
        MasterJenis frmMasterSatuan = new MasterJenis();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frmMasterSatuan).setVisible(true);
    }//GEN-LAST:event_kelolaJenisMouseClicked

    private void kelolaJenisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelolaJenisMousePressed
        // TODO add your handling code here:

        menuStok.setBackground(defaultColor);
        kelolaBarang.setBackground(defaultColor);
        kelolaJenis.setBackground(clickedColor);
        menuDashboard.setBackground(defaultColor);

        detailMenu.setText("Kelola Jenis Barang");

    }//GEN-LAST:event_kelolaJenisMousePressed

    private void jPanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseClicked
        // TODO add your handling code here:
        //String sql = "SELECT * FROM login WHERE username=? AND password=?";
        loginForm login = new loginForm();
        ImageIcon icon = new ImageIcon("src/images/logout.png");
        int pilih = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?" ,"Logout",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        if (pilih == JOptionPane.OK_OPTION){
            login.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.getRootFrame();
        }

    }//GEN-LAST:event_jPanelLogoutMouseClicked

    private void jPanelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseEntered
        // TODO add your handling code here:

        jPanelLogout.setBackground(penEnter);
        textLogout.setForeground(penDefault);
    }//GEN-LAST:event_jPanelLogoutMouseEntered

    private void jPanelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseExited
        // TODO add your handling code here:
        jPanelLogout.setBackground(penDefault);
        textLogout.setForeground(fontColorDefault);
    }//GEN-LAST:event_jPanelLogoutMouseExited

    private void jPanelLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMousePressed
        // TODO add your handling code here:
        jPanelLogout.setBackground(penDefault);
        textLogout.setForeground(clickedColor);
    }//GEN-LAST:event_jPanelLogoutMousePressed

    private void jPanelLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseReleased
        // TODO add your handling code here:

        jPanelLogout.setBackground(penEnter);
        textLogout.setForeground(penDefault);
    }//GEN-LAST:event_jPanelLogoutMouseReleased

    private void menuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMouseClicked
        // TODO add your handling code here:
        DashboardPegawaiFrame frame = new DashboardPegawaiFrame();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frame).setVisible(true);
    }//GEN-LAST:event_menuDashboardMouseClicked

    private void menuDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDashboardMousePressed
        // TODO add your handling code here:
        menuDashboard.setBackground(clickedColor);
        kelolaBarang.setBackground(defaultColor);
        menuStok.setBackground(defaultColor);
        kelolaJenis.setBackground(defaultColor);
        detailMenu.setText("Dashboard");
    }//GEN-LAST:event_menuDashboardMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void menuStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStokMouseClicked
        StokBarang frame = new StokBarang();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(frame).setVisible(true);
    }//GEN-LAST:event_menuStokMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel kelolaBarang;
    private javax.swing.JPanel kelolaJenis;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label_2;
    private javax.swing.JLabel label_3;
    private javax.swing.JPanel menuDashboard;
    private javax.swing.JPanel menuStok;
    private javax.swing.JLabel textLogout;
    // End of variables declaration//GEN-END:variables
}
