/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import database.koneksi;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author lanz1
 */
public class MasterBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasterBarang
     */
    public MasterBarang() {
        initComponents();

        show_barang_inJtable();
        updateCombo();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12 ));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32,136,203));
        jTable1.getTableHeader().setForeground(new Color(255,255,255));
        jTable1.setRowHeight(25);
    }
    
    koneksi k = new koneksi();
    Connection con = k.connection;
    
    public ArrayList<barang> getBarangList()
    {
       ArrayList<barang> barangList = new ArrayList<barang>();
       
       String query = "SELECT barang.kode_barang, barang.nama_barang,barang.stok_minimal,barang.harga_jual,barang.harga_beli, satuan.satuan FROM barang\n" +
"JOIN satuan ON barang.id_satuan = satuan.id_satuan";
       
       Statement st;
       ResultSet rs;
       
       try{
           st = con.createStatement();
           rs = st.executeQuery(query);
           
           barang Barang;           
           while(rs.next()){
               
               Barang = new barang(rs.getInt("kode_barang"),rs.getString("nama_barang"), 
                       rs.getString("satuan"), rs.getInt("stok_minimal"), 
                       rs.getDouble("harga_jual"), rs.getDouble("harga_beli"));
               barangList.add(Barang);
           }        
       }catch(Exception e){
           e.printStackTrace();
       }       
       return barangList;
    }
    
    
    public void show_barang_inJtable(){
        
        ArrayList<barang> list = getBarangList();
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        Object[] row = new Object[6];
        
        for(int i=0; i < list.size(); i++){
            row[0] = list.get(i).getKodeBarang();
            row[1] = list.get(i).getNamaBarang();
            row[2] = list.get(i).getSatuan();
            row[3] = list.get(i).getstokMinimal();
            row[4] = list.get(i).getHargaJual();
            row[5] = list.get(i).getHargaBeli();
            
            model.addRow(row);
        }       
    }

    //JCombobox Value
    private void updateCombo(){
    String query = "SELECT * FROM satuan";
    PreparedStatement ps;
    ResultSet rs;
    try{
    ps = con.prepareStatement(query);
    rs= ps.executeQuery();
    while(rs.next()){
    cbJenis.addItem(rs.getString("satuan"));
    }
    
    }catch(Exception ex){
    JOptionPane.showMessageDialog(null, "Data Kosong", "Information", JOptionPane.ERROR_MESSAGE);
    }
    
    }
        
    public void executeSQLQuery(String query, String pesan)
    {
        Statement st;
        
        try{
           st = con.createStatement();
            ImageIcon iconSucceed = new ImageIcon("src/images/checked.png");
            ImageIcon iconFailed = new ImageIcon("src/images/remove.png");
           if(st.executeUpdate(query) == 1){
               
               //refresh jtable data
               DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
               model.setRowCount(0);
               show_barang_inJtable();
               
                JOptionPane.showMessageDialog(null, "Data " +pesan+" Succesfully", "Information", JOptionPane.INFORMATION_MESSAGE, iconSucceed);
           }
           else{
               JOptionPane.showMessageDialog(null, "Data Not" +pesan, "Information", JOptionPane.INFORMATION_MESSAGE, iconFailed);          
           }
                 
       }catch(Exception e){
           e.printStackTrace();
       }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        cbJenis = new javax.swing.JComboBox<>();
        tfStokMinimal = new javax.swing.JTextField();
        tfHargaJual = new javax.swing.JTextField();
        tfHargaBeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(690, 560));

        jPanel1.setPreferredSize(new java.awt.Dimension(733, 579));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel1.setText("Kode");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        tfKode.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jPanel1.add(tfKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 230, 40));

        jLabel2.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel2.setText("Nama Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel3.setText("Stok Minimal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel4.setText("Modal Buat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel5.setText("Harga Jual");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jLabel6.setText("Jenis");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        tfNamaBarang.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jPanel1.add(tfNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 230, 40));

        jPanel1.add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 152, 40));

        tfStokMinimal.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jPanel1.add(tfStokMinimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, 40));

        tfHargaJual.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jPanel1.add(tfHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 230, 40));

        tfHargaBeli.setFont(new java.awt.Font(".SF NS Text", 0, 16)); // NOI18N
        jPanel1.add(tfHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 230, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama Barang", "Jenis", "Total Stok", "Harga Beli", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 670, 200));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset.png"))); // NOI18N
        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 120, -1));

        BtnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, -1));

        BtnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 110, -1));

        BtnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        
        
        if(jTable1.getSelectedRow()>0){
        int pilih = JOptionPane.showConfirmDialog(null, "Yakin ingin dihapus?", "Confirm",  JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(pilih == JOptionPane.OK_OPTION){
         String query = "DELETE FROM `barang` WHERE kode_barang="+tfKode.getText();
        
        executeSQLQuery(query, "Deleted");  
          
       
        tfKode.setText("");
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfNamaBarang.setText("");
        tfStokMinimal.setText("");
        tfKode.setEditable(true);
        }   
        }else{
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Barang Yang Akan Dihapus","Pesan Error",
                    JOptionPane.ERROR_MESSAGE);
            }
         
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        tfKode.setEditable(false);
              
        //menampilkan data yang di klik pada table ke dalam form      
        
        int i = jTable1.getSelectedRow();
        
        TableModel model = jTable1.getModel();
        
        tfKode.setText(model.getValueAt(i, 0).toString());
        tfNamaBarang.setText(model.getValueAt(i, 1).toString());
        cbJenis.getModel().setSelectedItem(model.getValueAt(i, 2).toString());
        tfStokMinimal.setText(model.getValueAt(i, 3).toString());
        tfHargaBeli.setText(model.getValueAt(i, 4).toString());
        tfHargaJual.setText(model.getValueAt(i, 5).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
       // int a = Integer.parseInt((String)cbJenis.getSelectedIndex());
//        int chosen = (Integer)cbJenis.getSelectedItem();
        String tanggal = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        
        String query = "INSERT INTO `barang`(`kode_barang`, `nama_barang`, `id_satuan`, `stok_minimal`, `tanggal`, `harga_jual`, `harga_beli`) "
                + "VALUES ('"+tfKode.getText()+"','"+tfNamaBarang.getText()+"','"+cbJenis.getSelectedIndex()+1+"','"+tfStokMinimal.getText()+"','"+tanggal+"','"+tfHargaJual.getText()+"','"+tfHargaBeli.getText()+"')";
        
        executeSQLQuery(query, "Inserted");
        tfKode.setText("");
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfNamaBarang.setText("");
        tfStokMinimal.setText("");
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        int cb = cbJenis.getSelectedIndex()+1;
        if(jTable1.getSelectedRow()>=0){
        String query = "UPDATE `barang` SET `nama_barang`='"+tfNamaBarang.getText()+"',"
                + "`id_satuan`='"+cb+"',"
                + "`stok_minimal`='"+tfStokMinimal.getText()+"',"
                + "`harga_jual`='"+tfHargaJual.getText()+"',"
                + "`harga_beli`='"+tfHargaBeli.getText()+"' "
                + "WHERE `kode_barang`="+tfKode.getText();
        
        executeSQLQuery(query, "Updated");        
        tfKode.setText("");
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfNamaBarang.setText("");
        tfStokMinimal.setText("");
        tfKode.setEditable(true);
        }else{
         JOptionPane.showMessageDialog(this, "Silahkan Pilih Barang Yang Akan di Ubah","Pesan Error",
         JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BtnUbahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tfKode.setText("");
        tfHargaBeli.setText("");
        tfHargaJual.setText("");
        tfNamaBarang.setText("");
        tfStokMinimal.setText("");
        tfKode.setEditable(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfHargaBeli;
    private javax.swing.JTextField tfHargaJual;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfStokMinimal;
    // End of variables declaration//GEN-END:variables
}
